### ISSUE TITLE
WhiteListSanitizer hangs on long/specific style attributes

### ISSUE THREAD

**Issue by haf7** [rails/rails-html-sanitizer#41] opened 2015-07-19 21:25 UTC
WhiteListSanitizer hangs on (for example) the following input:

`b2="<li class=\"my_next\" style=\"margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 5px; padding-right: 10px; padding-bottom: 5px; padding-left: 10px; border-top-width: 1px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; outline-width: 0px; outline-style: initial; outline-color: initial; line-height: normal; font-style: inherit; font-size: 11px; font-family: inherit; word-spacing: normal; vertical-align: baseline; list-style-type: none; list-style-position: initial; list-style-image: initial; border-top-style: solid; border-top-color: rgb(51, 51, 51); font: normal normal bold 11px/normal Arial, Helvetica, sans-serif; color: rgb(255, 255, 255); white-space: nowrap; cursor: pointer; text-indent: 0px; \">Play Next</li>"`
`white_list_sanitizer = Rails::Html::WhiteListSanitizer.new`
`white_list_sanitizer.sanitize(b2)`

Tested with rails 4.2.3

**Comment by mfazekas** [comment] 2015-08-05 22:00
probably related https://github.com/flavorjones/loofah/issues/90

**Comment by kaspth** [comment] 2015-08-09 11:04
I'm closing because this is an issue with Loofah, as @mfazekas mentioned: flavorjones/loofah#90. Thanks :heart:

**Closed by kaspth** 2015-08-09 11:04 UTC

**Comment by flavorjones** [comment] 2015-08-17 17:54
@haf7 Worth noting that I cannot reproduce hanging on your example, given Loofah v2.0.2 and Ruby 2.2.2.

But yes, https://github.com/flavorjones/loofah/issues/90 is probably related.
